# api_id and api_hash can be obtained from https://my.telegram.org
# bot_token can be obtained from https://t.me/botfather
# session_string can be obtained from https://repl.it/@subinps/GenerateStringSession
# sudo_users can be obtained from https://t.me/userinfobot

[pyrogram]
api_id = 23245104                                                      # required
api_hash = "2bbe8e4f5e88729c42c9800b20ecc0c4"                       # required
bot_token = "6575301465:AAH39zw_I-hNp6F_oaF8dLFZdlI21TdB-Go"                  # either bot_token or session_string is required
session_string = "BQFisTAABpRXf3VWx-Vl68NeLy3yQtNrWFA074T5FQYP5TQUlXt35fL_BwmO5akI-84OzmhRL4iZU3iCUhZg90R8mSAluNKatxr8TTTXsFEalZ9S4wJbCy_dnr6umArJ5WVgMaAfT0M1qcBQnCisKioDz8dES2JA1tiN2QKCyoBOEBZo9sfa9pTszGh4-CW66umvWVBy7fkAAtKt7TGQ0pztzEBSWlBOAH-HCg-Kh0Y7lgYQ6C6lMhdA-NN0VkYhN8PwPEMU0K9CoC2QdeUlhe-M1AwZBE7g3O5BMUmiMrp7bgwNPuj-EQhkOChxAwW4KR4nuIn8KnR7CZhWO4_OHOQOBsr-GQAAAAGdAcm3AA" # either bot_token or session_string is required
sudo_users = [6929107383, 6929107383]                                 # optional


# chat ids can be obtained from https://t.me/getidsbot
# All chats must be in the format of [-]1001234567890
# You can add multiple chats in the format of a list
# You can also add multiple chats in the format of a list of lists
# Atleast one chat must be added

[[chats]]
from = -1908578896        # required
to = 1998483689              # required
replace = { "old" = "new" } # optional

[[chats]]
from = [123456789, -100123456789]               # required
to = 123456789                                  # required
replace = { "only_apply_to_this_chat" = "new" } # optional

[[chats]]
from = -100123456789            # required
to = [123456789, -100123456789] # required

[[chats]]
from = [123456789, -100123456789] # required
to = [123456789, -100123456789]   # required
